-- MySQL Script generated by MySQL Workbench
-- qui 14 dez 2017 21:48:48 -02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema php_test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema php_test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `php_test` DEFAULT CHARACTER SET utf8 ;
USE `php_test` ;

-- -----------------------------------------------------
-- Table `php_test`.`Postagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `php_test`.`Postagem` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL,
  `autor` VARCHAR(45) NULL,
  `conteudo` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO Postagem(titulo, autor, conteudo) VALUES
("Titulo 1", "Autor 1", "Teste"),
("Titulo 2", "Autor 2", "Teste"),
("Untitled", "Eu", "Desnecessário");
